### PR TITLE
Move to Ruby 2.7+

### PR DESCRIPTION
**Pull request by ekohl**
Ruby 2.5 and 2.6 are unsupported and providing Ruby 3 compatibility is easier with Ruby 2.7 as the lower bound.

It should be noted that from testing it appears Ruby 3 support is broken. Should the upper bound be lower to `< 3` for now?

### CODE REVIEW

**Comment by adamruzicka** [comment]
> Should the upper bound be lower to < 3 for now?

I'd say yes.

**Comment by ekohl** [comment]
The diffs would be smaller if https://github.com/svenfuchs/safemode/pull/43 was merged, but I've updated it now.

**Comment by adamruzicka** [comment]
Could we also drop `lib/rubyparser_bug.rb` while we're at it?

**Comment by ekohl** [comment]
Done

**Comment by adamruzicka** [comment]
Thank you @ekohl !

**Pull request merged**
